# generated by datamodel-codegen:
#   filename:  f488.json
#   timestamp: 2025-06-24T00:09:59+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Pokemon(BaseModel):
    name: str
    url: str


class Sprites(BaseModel):
    back_default: str
    back_female: None
    back_shiny: str
    back_shiny_female: None
    front_default: str
    front_female: None
    front_shiny: str
    front_shiny_female: None


class Type1(BaseModel):
    name: str
    url: str


class Type(BaseModel):
    slot: int
    type: Type1


class VersionGroup(BaseModel):
    name: str
    url: str


class PokemonForm(BaseModel):
    form_name: str
    form_names: List
    form_order: int
    id: int
    is_battle_only: bool
    is_default: bool
    is_mega: bool
    name: str
    names: List
    order: int
    pokemon: Pokemon
    sprites: Sprites
    types: List[Type]
    version_group: VersionGroup
